# inside services/service-a/Dockerfile
FROM node:20-alpine
WORKDIR /app

# Copy service-a files
COPY services/service-a/ .

# Copy shared package
COPY packages/shared/ ./shared

RUN npm install ./shared
RUN npm install

CMD ["npm", "run", "start"]
