version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shared_arch
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  service-a:
    build:
      context: .
      dockerfile: ./services/service-a/Dockerfile
    container_name: service-a
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: shared_arch
    ports:
      - "3000:3000"

  service-b:
    build:
      context: .
      dockerfile: ./services/service-b/Dockerfile
    container_name: service-b
    depends_on:
      - service-a
    environment:
      SERVICE_A_URL: http://service-a:3000
    ports:
      - "3001:4000"

volumes:
  db_data:
