version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shared_arch
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  service-a:
    build: ./services/service-a
    container_name: service-a
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: shared_arch
    ports:
      - "3000:3000"

  service-b:
    build: ./services/service-b
    container_name: service-b
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: shared_arch
    ports:
      - "3001:3001"

volumes:
  db_data: