# inside services/service-b/Dockerfile
FROM node:20-alpine
WORKDIR /app

# Copy service-b files
COPY services/service-b/ .

# Copy shared package
COPY packages/shared/ ./shared

RUN npm install ./shared
RUN npm install

CMD ["npm", "run", "start"]
